---
- name: Add mongodb gpg key
  apt_key:
    keyserver: "{{mongodb_keyserver}}"
    id: "{{mongodb_key_id}}"
    state: present

- name: Add the repo
  apt_repository:
    repo: "{{mongodb_repo_uri}}"
    state: present

- name: Install MongoDB package
  apt:
    name: "{{mongodb_pkg_name}}"
    state: present
    update_cache: yes

- name: Template of mongod.conf
  template:
    src: mongod.conf.j2
    dest: /etc/mongod.conf
    mode: 0644
  vars:
    port: "{{mongodb_port}}"
    bind_ip: "{{mongodb_bind_ip}}"
    dbpath: "{{mongodb_dbpath}}"
    logfile: "{{mongodb_logfile}}"
  notify: Restart_mongodb.service

- name: Get stats of monitrc
  stat:
    path: "{{monit_dir}}/monitrc"
    get_md5: no
    get_checksum: no
  register: st_monitrc

- name: Template of mongodb.monit
  template:
    src: mongodb.monit.j2
    dest: "{{monit_includedir}}/mongodb.monit"
    mode: 0644
  vars:
    start_program: '/usr/bin/systemctl start {{mongodb_service_name}}'
    stop_program: '/usr/bin/systemctl stop {{mongodb_service_name}}'
  when: st_monitrc.stat.exists
  notify: Restart_monit.service
